### PR TITLE
Form handlers

### PR DESCRIPTION
**Pull request by sysadminwatdo**
* Names for form fields and action/method in contact.html
* Form handler options with and without database writes. Both send emails to site owner and submitter.  Table is created if it does not exist as long as credentials are supplied. (form-handler.php and form-handler-nodb.php
* Reference to form handler in README.md
* No styles on response page.  Could just as easily do a header redirect to the homepage, that might be a better experience.

### CODE REVIEW

**Comment by davidtmiller** [comment]
I'm not super familiar with creating this sort of stuff, so my question is how secure are these scripts? Thank you so much for taking the time to write this!

**Comment by sysadminwatdo** [comment]
Where the database is used, the inputs are sanitized with mysqli_real_escape_string so that a form submitted couldn't enter their name as "DROP TABLE;" and have that executed on the db.

I used POST instead of GET because it's somewhat safer (form inputs are not sent as part of the URL string) and because it makes for a prettier experience for the same reason.

I suppose someone could write a bot to just keep spamming the form with garbage data over and over and over again, but that's really always a risk.  The mail() function depends on that being available on their server, of course.  I could roll in Swiftmailer, but at the end of the day it's a ton more code and more configuration, for little value.  As far as I've seen, mail() is usually available on most hosting except to people who have abused it.

As far as time, it was quick and easy. Not a big deal. :)

**Comment by davidtmiller** [comment]
Thanks for the information. On some other forms that I've got on Start Bootstrap I have the jqBootstrapValidation plugin running for some form validation. Does this have validation built in?

**Comment by sysadminwatdo** [comment]
No validation and the db fields are just text fields so they'll accept varied formats of phone numbers and such.  That plugin would be a useful addition.

**Pull request merged**
